spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-controle-usuario
              uri: http://localhost:9091
              predicates:
                - Path=/auth/**

            - id: ms-escala
              uri: http://localhost:9092
              predicates:
                - Path=/avaliador/**

            - id: ms-sollux
              uri: http://localhost:9093
              predicates:
                - Path=/planilha/**

            - id: ms-advogado
              uri: http://localhost:9094
              predicates:
                - Path=/advogado/**

            - id: ms-pauta
              uri: http://localhost:9094
              predicates:
                - Path=/pautas/**

            - id: ms-pauta
              uri: http://localhost:9094
              predicates:
                - Path=/orgao-julgador/**

  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origin-patterns: "*"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600



